CREATE TABLE dbo.Clientes (
    id INT IDENTITY(1,1) PRIMARY KEY,
    codigo INT NULL,
    razao_social VARCHAR(255) NULL,
    nome_fantasia VARCHAR(255) NULL,
    tipo CHAR(1) NULL,
    cpf VARCHAR(14) NULL,
    cnpj VARCHAR(18) NULL,
    tipo_contribuinte VARCHAR(50) NULL,
    inscricao_estadual VARCHAR(50) NULL,
    inscricao_municipal VARCHAR(50) NULL,
    situacao INT NULL,
    regime_tributario VARCHAR(50) NULL,
    data_nascimento DATETIME NULL,
    numero_pis_inss VARCHAR(50) NULL,
    sexo VARCHAR(10) NULL,
    observacao VARCHAR(255) NULL,
    data_cadastro DATETIME NULL,
    cliente BIT NULL,
    fornecedor BIT NULL,
    vendedor BIT NULL,
    entregador BIT NULL,
    temp_data_ultima_alteracao VARCHAR(50) NULL,
    email VARCHAR(255) NULL,
    email_principal BIT NULL,
    tipo_endereco VARCHAR(50) NULL,
    endereco VARCHAR(255) NULL,
    numero VARCHAR(50) NULL,
    complemento VARCHAR(255) NULL,
    bairro VARCHAR(255) NULL,
    uf_cidade VARCHAR(10) NULL,
    uid_cidade VARCHAR(255) NULL,
    cep VARCHAR(20) NULL,
    referencia VARCHAR(255) NULL,
    tipo_telefone VARCHAR(50) NULL,
    telefone VARCHAR(50) NULL,
    nome_contato VARCHAR(255) NULL,
    telefone_principal BIT NULL
);

CREATE TABLE dbo.Produtos (
    id INT IDENTITY(1,1) PRIMARY KEY,
    codigo INT NULL,
    descricao VARCHAR(255) NULL,
    codigo_barras VARCHAR(255) NULL,
    referencia VARCHAR(255) NULL,
    ativo BIT NULL,
    uid_grupo VARCHAR(255) NULL,
    uid_marca VARCHAR(255) NULL,
    uid_unidade_medida VARCHAR(255) NULL,
    preco_custo DECIMAL(18,2) NULL,
    margem_lucro DECIMAL(18,2) NULL,
    preco_venda DECIMAL(18,2) NULL,
    id_ncm VARCHAR(255) NULL,
    cest VARCHAR(50) NULL,
    estoque INT NULL,
    codigo_anp VARCHAR(50) NULL,
    percentual_glp_petroleo DECIMAL(18,2) NULL,
    percentual_gas_nacional DECIMAL(18,2) NULL,
    percentual_gas_importado DECIMAL(18,2) NULL,
    valor_partida DECIMAL(18,2) NULL,
    uid_unidade_tributavel VARCHAR(255) NULL,
    quantidade_unidade_tributavel DECIMAL(18,2) NULL,
    data_ultima_atualizacao DATETIME NULL,
    codigo_balanca VARCHAR(50) NULL,
    departamento INT NULL
);

CREATE TABLE dbo.ContasReceber (
    id INT IDENTITY(1,1) PRIMARY KEY,
    uid_crediario_proprio VARCHAR(255) NULL,
    uid_empresa VARCHAR(255) NULL,
    uid_integracao VARCHAR(255) NULL,
    uid_venda VARCHAR(255) NULL,
    numero_parcela VARCHAR(50) NULL,
    total_parcela VARCHAR(50) NULL,
    uid_participante VARCHAR(255) NULL,
    data_emissao DATETIME NULL,
    data_vencimento_original DATETIME NULL,
    data_vencimento DATETIME NULL,
    valor_crediario DECIMAL(18,2) NULL,
    valor_juro DECIMAL(18,2) NULL,
    valor_desconto DECIMAL(18,2) NULL,
    valor_pagar DECIMAL(18,2) NULL,
    valor_pago DECIMAL(18,2) NULL,
    valor_saldo DECIMAL(18,2) NULL,
    uid_usuario_inclusao VARCHAR(255) NULL,
    data_hora_inclusao DATETIME NULL,
    uid_usuario_alteracao VARCHAR(255) NULL,
    data_hora_alteracao DATETIME NULL,
    data_hora_cancelamento DATETIME NULL,
    uid_usuario_cancelamento VARCHAR(255) NULL,
    data_quitacao DATETIME NULL,
    codigo INT NULL,
    observacao_crediario VARCHAR(255) NULL
);

CREATE TABLE dbo.ContasPagar (
    id INT IDENTITY(1,1) PRIMARY KEY,
    uid_contas_pagar VARCHAR(255) NULL,
    uid_empresa VARCHAR(255) NULL,
    uid_integracao VARCHAR(255) NULL,
    uid_compra VARCHAR(255) NULL,
    numero_parcela VARCHAR(50) NULL,
    total_parcela VARCHAR(50) NULL,
    uid_fornecedor VARCHAR(255) NULL,
    data_emissao DATETIME NULL,
    data_vencimento_original DATETIME NULL,
    data_vencimento DATETIME NULL,
    valor_crediario DECIMAL(18,2) NULL,
    valor_juro DECIMAL(18,2) NULL,
    valor_desconto DECIMAL(18,2) NULL,
    valor_pagar DECIMAL(18,2) NULL,
    valor_pago DECIMAL(18,2) NULL,
    valor_saldo DECIMAL(18,2) NULL,
    uid_usuario_inclusao VARCHAR(255) NULL,
    data_hora_inclusao DATETIME NULL,
    uid_usuario_alteracao VARCHAR(255) NULL,
    data_hora_alteracao DATETIME NULL,
    data_hora_cancelamento DATETIME NULL,
    uid_usuario_cancelamento VARCHAR(255) NULL,
    data_quitacao DATETIME NULL,
    codigo INT NULL,
    observacao_contas_pagar VARCHAR(255) NULL
);

CREATE TABLE dbo.NFe (
    id INT IDENTITY(1,1) PRIMARY KEY,
    cnpj_emitente VARCHAR(18) NULL,
    numero_documento VARCHAR(255) NULL,
    codigo_numerico VARCHAR(255) NULL,
    chave VARCHAR(255) NULL,
    protocolo VARCHAR(255) NULL,
    recebido_em DATETIME NULL,
    xml_autorizado VARCHAR(MAX) NULL
);

CREATE TABLE dbo.NFCe (
    id INT IDENTITY(1,1) PRIMARY KEY,
    serie VARCHAR(50) NULL,
    numero_documento VARCHAR(255) NULL,
    codigo_numerico VARCHAR(255) NULL,
    chave VARCHAR(255) NULL,
    tag_id VARCHAR(255) NULL,
    protocolo VARCHAR(255) NULL,
    recebido_em DATETIME NULL,
    xml_autorizado VARCHAR(MAX) NULL
);

CREATE TABLE dbo.Notas (
    id INT IDENTITY(1,1) PRIMARY KEY,
    cnpj_fornecedor VARCHAR(18) NULL,
    uid_fornecedor VARCHAR(255) NULL,
    numero_documento VARCHAR(255) NULL,
    serie VARCHAR(50) NULL,
    chave VARCHAR(255) NULL,
    xml_final VARCHAR(MAX) NULL
);
